FROM golang:1.8-alpine

RUN apk -U add musl-dev gcc make git

RUN mkdir -p /go/src/s3autoindex
WORKDIR /go/src/s3autoindex

CMD set -x \
    && go get -v -d ./... \
    && go build -a -installsuffix cgo -ldflags "-linkmode external -extldflags \"-static\"" -v -o bin/s3autoindex ./...
